name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      -   name: Setup SSH Keys and known_hosts 🔑
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
              mkdir -p ~/.ssh
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              ssh-agent -a $SSH_AUTH_SOCK > /dev/null
              ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Install and Build 🔧
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          yarn install
          yarn build
          
      - name: Store artifacts 📦
        uses: actions/upload-artifact@v2.2.4
        with:
          path: dist
