name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          ref: 'feature/detailspage'
      - name: Lint 🚚
        run: |
          yarn lint